owner: justdanielndev
repo: uptime
customStatusWebsitePackage: "@justdanielndev/status-page"

sites:
  - name: Portfolio
    url: https://zoe.rocks
  - name: CDN
    url: https://cdn.isitzoe.dev
  - name: Hack Club Wrapped
    url: https://wrapped.isitzoe.dev

status-website:
  cname: status.isitzoe.dev
  logoUrl: https://status.isitzoe.dev/logo.svg
  name: "Zoe's Uptime Page"
  themeUrl: https://status.isitzoe.dev/theme.css
  introTitle: "**Hii!** :3 this is the status page for all my projects."
  introMessage: "It uses GitHub Actions to monitor the status of my websites and APIs. Extremely cool if you ask me! :D Btw, if you notice any issues, please feel free to reach out to me!"
  navbar:
    - title: Status
      href: /
    - title: My Portfolio
      href: https://isitzoe.dev
